import '../node_modules/@vanillawc/wc-codemirror/index.js'
import '../node_modules/@vanillawc/wc-codemirror/mode/javascript/javascript.js'

import './react-simple.js'
import './lit-simple.js'
import './react-stateful.js'
import './lit-stateful.js'
import './react-app.js'
import './lit-app.js'
import './react-external.js'
import './lit-external.js'
import './react-hooks.js'
import './lit-hooks.js'
